### ISSUE TITLE
meet error in test (unknown error at /pytorch/aten/src/THC/THCTensorRandom.cu:25)

### ISSUE THREAD

**Issue by moonuke** [huanghoujing/person-reid-triplet-loss-baseline#12]
when I run test.
I meet error like:

THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorRandom.cu line=25 error=30 : unknown error
Traceback (most recent call last):
  File "train.py", line 561, in <module>
    main()
  File "train.py", line 347, in main
    model_w = DataParallel(model)
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 102, in __init__
    _check_balance(self.device_ids)
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 17, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 290, in get_device_properties
    init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 143, in init
    _lazy_init()
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCTensorRandom.cu:25

it seems like when doing TensorRandom it happens?
how to deal with it ?
very thx

**Comment by huanghoujing** [comment]
Which pytorch version did you use? BTW, can you provide (1) your command (2) the output of linux command `nvidia-smi`?

**Comment by moonuke** [comment]
**my command is:**
```
cd /home/moonuke/re-id/triplet_loss_baseline/script/experiment/ \
python train.py \
-d '(0,)' \
--only_test true \
--dataset market1501 \
--last_conv_stride 1 \
--normalize_feature false \
--exp_dir /home/moonuke/re-id/triplet_loss_baseline/person-reid-triplet-loss-baseline-model-weights/market1501_stride1/log/ \
--model_weight_file /home/moonuke/re-id/triplet_loss_baseline/person-reid-triplet-loss-baseline-model-weights/market1501_stride1/
```


**the output of linux command is :** 
```
cfg.__dict__
{'base_lr': 0.0002,
 'ckpt_file': '/home/moonuke/re-id/triplet_loss_baseline/person-reid-triplet-loss-baseline-model-weights/market1501_stride1/log/ckpt.pth',
 'crop_prob': 0,
 'crop_ratio': 1,
 'dataset': 'market1501',
 'epochs_per_val': 10000000000.0,
 'exp_decay_at_epoch': 76,
 'exp_dir': '/home/moonuke/re-id/triplet_loss_baseline/person-reid-triplet-loss-baseline-model-weights/market1501_stride1/log/',
 'ids_per_batch': 32,
 'im_mean': [0.486, 0.459, 0.408],
 'im_std': [0.229, 0.224, 0.225],
 'ims_per_id': 4,
 'last_conv_stride': 1,
 'log_to_file': True,
 'lr_decay_type': 'exp',
 'margin': 0.3,
 'model_weight_file': '/home/moonuke/re-id/triplet_loss_baseline/person-reid-triplet-loss-baseline-model-weights/market1501_stride1/',
 'normalize_feature': False,
 'only_test': True,
 'prefetch_threads': 2,
 'resize_h_w': (256, 128),
 'resume': False,
 'run': 1,
 'scale_im': True,
 'seed': None,
 'staircase_decay_at_epochs': (101, 201),
 'staircase_decay_multiply_factor': 0.1,
 'stderr_file': '/home/moonuke/re-id/triplet_loss_baseline/person-reid-triplet-loss-baseline-model-weights/market1501_stride1/log/stderr_2018-06-04_10:23:05.txt',
 'stdout_file': '/home/moonuke/re-id/triplet_loss_baseline/person-reid-triplet-loss-baseline-model-weights/market1501_stride1/log/stdout_2018-06-04_10:23:05.txt',
 'steps_per_log': 20,
 'sys_device_ids': (0,),
 'test_batch_size': 32,
 'test_final_batch': True,
 'test_mirror_type': None,
 'test_set_kwargs': {'batch_dims': 'NCHW',
                     'batch_size': 32,
                     'final_batch': True,
                     'im_mean': [0.486, 0.459, 0.408],
                     'im_std': [0.229, 0.224, 0.225],
                     'mirror_type': None,
                     'name': 'market1501',
                     'num_prefetch_threads': 2,
                     'part': 'test',
                     'prng': <module 'numpy.random' from '/home/moonuke/tensorflow/local/lib/python2.7/site-packages/numpy/random/__init__.pyc'>,
                     'resize_h_w': (256, 128),
                     'scale': True,
                     'shuffle': False},
 'test_shuffle': False,
 'total_epochs': 150,
 'train_final_batch': True,
 'train_mirror_type': 'random',
 'train_set_kwargs': {'batch_dims': 'NCHW',
                      'crop_prob': 0,
                      'crop_ratio': 1,
                      'final_batch': True,
                      'ids_per_batch': 32,
                      'im_mean': [0.486, 0.459, 0.408],
                      'im_std': [0.229, 0.224, 0.225],
                      'ims_per_id': 4,
                      'mirror_type': 'random',
                      'name': 'market1501',
                      'num_prefetch_threads': 2,
                      'part': 'trainval',
                      'prng': <module 'numpy.random' from '/home/moonuke/tensorflow/local/lib/python2.7/site-packages/numpy/random/__init__.pyc'>,
                      'resize_h_w': (256, 128),
                      'scale': True,
                      'shuffle': True},
 'train_shuffle': True,
 'trainset_part': 'trainval',
 'val_set_kwargs': {'batch_dims': 'NCHW',
                    'batch_size': 32,
                    'final_batch': True,
                    'im_mean': [0.486, 0.459, 0.408],
                    'im_std': [0.229, 0.224, 0.225],
                    'mirror_type': None,
                    'name': 'market1501',
                    'num_prefetch_threads': 2,
                    'part': 'val',
                    'prng': <module 'numpy.random' from '/home/moonuke/tensorflow/local/lib/python2.7/site-packages/numpy/random/__init__.pyc'>,
                    'resize_h_w': (256, 128),
                    'scale': True,
                    'shuffle': False},
 'weight_decay': 0.0005}
------------------------------------------------------------
----------------------------------------
market1501 test set
----------------------------------------
NO. Images: 31969
NO. IDs: 751
NO. Query Images: 3368
NO. Gallery Images: 15913
NO. Multi-query Images: 12688
----------------------------------------
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /home/moonuke/.torch/models/resnet50-19c8e357.pth
100.0%
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCTensorRandom.cu line=25 error=30 : unknown error
Traceback (most recent call last):
  File "train.py", line 561, in <module>
    main()
  File "train.py", line 347, in main
    model_w = DataParallel(model)
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 102, in __init__
    _check_balance(self.device_ids)
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 17, in _check_balance
    dev_props = [torch.cuda.get_device_properties(i) for i in device_ids]
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 290, in get_device_properties
    init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 143, in init
    _lazy_init()
  File "/home/moonuke/.local/lib/python2.7/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCTensorRandom.cu:25

```

**Comment by moonuke** [comment]
my torch version is 0.4.0

$ nvidia-smi
Mon Jun  4 11:17:10 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:01:00.0  On |                  N/A |
|  0%   51C    P8    16W / 260W |    206MiB /  8112MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1113      G   /usr/lib/xorg/Xorg                           132MiB |
|    0      2277      G   compiz                                        71MiB |
+-----------------------------------------------------------------------------+

**Comment by moonuke** [comment]
I fix this problem. It was caused bu pytorch0.4 system.
use pytorch 0.3 version is ok

**Comment by huanghoujing** [comment]
OK, thank you for your feedback.
